create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  draw_index integer not null,
  numbers integer[] not null,
  bonus integer,
  created_at timestamptz default now()
);

alter table public.lotto_draws enable row level security;

create policy if not exists "Allow public insert"
  on public.lotto_draws
  for insert
  to public
  with check (true);

create policy if not exists "Allow public read"
  on public.lotto_draws
  for select
  to public
  using (true);
